name: Run JavaScript tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          packages/etna/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: NPM install
      run: |
        cd packages/etna-js
        npm install
    - name: Run UI test suite
      run: |
        cd packages/etna-js
        npm run test