configfile: "config.yaml"

rule all:
    input:
        "output/word_count.txt"

rule extract_words:
    input:
        config=["extract_words"]["input"]["file"]
    output:
        "intermediate/first_{n}_words_{filename}"
    params:
        n=config["extract_words"]["num_words"]
    run:
        with open(input[0], 'r') as infile, open(output[0], 'w') as outfile:
            words = infile.read().split()[:params.n]
            outfile.write(' '.join(words) + '\n')

rule count_words:
    input:
        "intermediate/first_{n}_words_{filename}"
    output:
        "output/word_count.txt"
    shell:
        "wc -w {input} > {output}"