configfile: "config.yaml"

rule all:
    input:
        thumbnail="output/thumbnail.png"

rule get_dataset_and_summarize:
    params:
        dataset_name=config["dataset_name"]
    output:
        scdata="dataset/scdata.Rds",
        plotting_options="dataset/plotting_options.json",
        discrete_metadata_summary="dataset/discrete_metadata_summary.json",
        all_opts="dataset/all_opts.json",
        continuous_opts="dataset/continuous_opts.json",
        discrete_opts="dataset/discrete_opts.json",
        reduction_opts="dataset/reduction_opts.json"
    script:
        "scripts/get_dataset_and_summarize.R"

rule plot_setup_ui:
    input:
        plotting_options="dataset/plotting_options.json"
    output:
        plot_settings="temps/plot_setup.json"

rule make_plot:
    input:
        scdata="dataset/scdata.Rds",
        plot_setup="temps/plot_setup.json",
        plotting_options="dataset/plotting_options.json"
    output:
        plot_out="output/plot.out",
        thumbnail="output/thumbnail.png",
        plot_Rds="output/plot.Rds"
    script:
        "scripts/make_dittoSeq_plot.R"

rule display_plot_ui:
    input:
        plot_out="output/plot.out"

rule download_plot_Robj_ui:
    input:
        plot_Rds="output/plot.Rds"