source 'https://rubygems.org'

ruby '~> 2.5'

gem 'rack'
gem 'pg'
gem 'sequel'
gem 'fog-aws'
gem 'etna', git: 'https://github.com/mountetna/monoetna.git', branch: 'refs/artifacts/gem-etna/8995c01822a417a29c8705b031a9926586040cb3'

group :test do
  gem 'rspec'
  gem 'rack-test', require: "rack/test"
  gem 'simplecov'
  gem 'webmock'
  gem 'factory_bot'
  gem 'timecop'
  gem 'database_cleaner'
  gem 'pry'
  gem 'pry-byebug'
  gem 'ruby-debug-ide'
  gem 'debase'
end

