# Rubygem doesn't provide a great hook for executing completion or shared data on installing a gem by default,
# but it does provide an extension installation hook in the form of extconf.rb.
# This file does not need to do much but is required for extconf.rb to succeed.
all:
	true

install:
	true