volumes:
  gnomon-log-dir:
    driver: local
  gnomon-tmp-dir:
    driver: local
  gnomon-public-dir:
    driver: local
  gnomon-data-dir:
    driver: local
  gnomon-db-data:
    driver: local
  gnomon-opt-dir:
    driver: local
  gnomon-node-modules:
    driver: local
      
x-base-etna-service:
  &base-etna-service # Base configuration used by most etna services.
  image: etna-base
  volumes: &base-etna-service-volumes
    - .:/app:delegated
    - gnomon-log-dir:/app/log:rw
    - gnomon-tmp-dir:/app/tmp:rw
    - gnomon-public-dir:/app/public:rw
    - gnomon-data-dir:/app/data:rw
    - gnomon-opt-dir:/usr/opt:rw
    - ../etna:/etna:delegated
  environment: &base-etna-env
    'GNOMON_ENV': 'development'
    APP_NAME: 'gnomon'
  entrypoint: /entrypoints/development.sh

  networks:
    default:
    edge_net:
  extra_hosts:
    - 'metis.development.local:172.16.238.10'
    - 'magma.development.local:172.16.238.10'
    - 'janus.development.local:172.16.238.10'
    - 'timur.development.local:172.16.238.10'
    - 'rtemis.development.local:172.16.238.10'
    - 'archimedes.development.local:172.16.238.10'
    - 'polyphemus.development.local:172.16.238.10'
    - 'gnomon.development.local:172.16.238.10'

x-base-etna-services:
  &base-etna-services # Default list of services an etna app may have.
  'gnomon_app': &base-etna-app # The ruby webserver
    <<: *base-etna-service
    command: ./bin/puma.sh

  'gnomon_webpack':
    &base-etna-webpack # The ruby webpack server watching for changes
    <<: *base-etna-service
    command: npm run webpack

  'gnomon_app_fe':
    &base-etna-fe # The application level apache frontend serving static assets, data, and proxying the main app.
    image: etna-apache
    volumes:
      - gnomon-public-dir:/app/public:ro
    depends_on:
      - 'gnomon_app'
    entrypoint: /entrypoints/development_app_fe.sh
    command: ['httpd', '-DFOREGROUND']
    environment:
      APP_NAME: 'gnomon_app_fe'

version: "3.4"

networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

services:
  <<: *base-etna-services
