BootStrap: localimage
From: /home/danb/r-base/r-base.sif

%labels
    Author Daniel Bunis
    Maintainer Daniel Bunis
    R_Version 4.4
    python_version 3.8
    # Seurat_Version 4.3.0

%runscript
    cd /app
    exec "${@}"

%files
    functions /app/archimedes-r/libraries
    install_deps.R /app/install_deps.R

%post
    # Install R packages
    cd /app
    Rscript install_deps.R

    # Cleanup
    rm -rf /var/lib/apt/lists/*
    rm -f /app/install_deps.R
    rm -rf /opt/get-pip.py
