version: '3.8'

# Intended for agents that run in global deploy node, on most or all nodes, for service health purposes.
services:
  sync-stacks-to-git:
    image: etnaagent/swarm-keeper:production
    deploy:
      labels:
        - autoupdate=true
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        delay: 300s
    secrets:
      - git-auth.env
      - portainer-auth.env
    command:
      - bash
      - -c
      - |
        set -eo pipefail
        source /usr/lib/swarm-keeper
        updateGitSources
  agent:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    ports:
      - 7100:8080
  service-deployer:
    image: etnaagent/service-deployer:production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autodeployed:/deployed
    secrets:
      - slack_webhook_url
      - service-deployer-docker-login
    deploy:
      labels:
        - autoupdate=true
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        delay: 300s

volumes:
  autodeployed:

secrets:
  slack_webhook_url:
    external: true
  service-deployer-docker-login:
    external: true
  git-auth.env:
    external: true
  portainer-auth.env:
    external: true