version: '3.8'

services:
  postgres:
    image: postgres:10.19
    environment:
      POSTGRES_DB: "magma"
      POSTGRES_PASSWORD_FILE: /run/secrets/password
      POSTGRES_USER: developer
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.volumes.big-shared == true
          - node.labels.psql.primary == true
    networks:
      - db
    secrets:
      - source: db-pw
        target: password

  app:
    environment:
      - APP_NAME=magma
      - MAGMA_ENV=production
      - ETNA__PRODUCTION_FILE=/app/env.yml
      - ETNA__PRODUCTION__DB__PASSWORD_FILE=/run/secrets/db-password
      - ETNA__PRODUCTION__USER_HASH_SECRET=/run/secrets/user-hash-secret
      - ETNA__PRODUCTION__HMAC_KEYS__METIS_FILE=/run/secrets/production-metis-hmac
      - ETNA__PRODUCTION__HMAC_KEYS__MAGMA_FILE=/run/secrets/production-magma-hmac
    command:
      - bash
      - -c
      - |
        set -e
        export METRICS_PW="$$(cat /run/secrets/metrics-pw)"
        exec /bin/deploy.sh migrate -- /app/bin/puma.sh
    image: etnaagent/magma:production

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      labels:
        - autoupdate=true
        - prometheus-etna=1 # 3000
      resources:
        limits:
          cpus: '4.0'
          memory: 8gb
        reservations:
          cpus: '2.0'
          memory: 4gb
      placement:
        constraints:
          - node.labels.is_edge != true
          - node.labels.volumes.data3 == true
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 1s
      test: bash -c 'curl -f -X OPTIONS http://localhost:3000 || exit 1'
      timeout: 5s
    configs:
      - source: config
        target: /app/config.yml
      - source: env
        target: /app/env.yml
    volumes:
      - backups:/backups
    networks:
      db:
      prometheus:
      fe:
        aliases:
          - magma_app
    secrets:
      - production-metis-hmac
      - production-magma-hmac
      - metrics-pw
      - user-hash-secret
      - source: db-pw
        target: db-password

  app_fe:
    environment:
      - APP_NAME=magma
      - MAGMA_ENV=production
    image: etnaagent/magma_app_fe:production
    networks:
      - edge_bridge
      - fe
    volumes:
      - app_public:/app/public:nocopy
    # Notably, apache needs to start as super user but it immediately downgrades
    # its own user permissions after bootup.  See the includes.
    user: 0:3000 # su:browser
    configs:
      - source: browser.system.include
        target: /usr/opt/httpd.conf.d/browser.system.include
    deploy:
      labels:
        - autoupdate=true
      placement:
        constraints:
          - node.labels.volumes.big-shared == true

  app_assets_deployer:
    environment:
      - APP_NAME=magma
      - MAGMA_ENV=production

    command: /bin/deploy.sh syncAssets -- true # Sync the assets to the shared data volume and stop.
    image: etnaagent/magma:production
    volumes:
      - app_public:/sync-assets:nocopy

    user: 0:3000
    deploy:
      labels:
        - autoupdate=true
      restart_policy:
        condition: none
      mode: replicated
      placement:
        constraints:
          - node.labels.volumes.big-shared == true
volumes:
  app_public:
    name: magma_production_app_public
    driver: local
    driver_opts:
      type: nfs
      o: addr=mtetna-nfs1,nolock,noatime,suid,nodev,retry=16,proto=tcp,nfsvers=3
      device: ":/cache/magma/app_public"
  db:
    name: "magma_production_db"
    driver: local
    driver_opts:
      type: nfs
      o: addr=mtetna-nfs1,nolock,noatime,suid,nodev,retry=16,proto=tcp,nfsvers=3,hard,intr
      device: ":/cache/postgres/magma"
  backups:
    name: "magma_production_backups"
    driver: local
    driver_opts:
      type: nfs
      o: addr=mtetna-nfs1,nolock,noatime,suid,nodev,retry=16,proto=tcp,nfsvers=3,hard,intr
      device: ":/cache/magma/backups"

configs:
  browser.system.include:
    name: ${BROWSER_SYSTEM_INCLUDE:-browser.system.include}
    external: true
  config:
    external: true
    name: ${APP_CONFIG:-magma.production.yml}
  env:
    external: true
    name: ${ENV_CONFIG:-etna.production.yml}

secrets:
  user-hash-secret:
    external: true
    name: ${USER_HASH_SECRET:-user-hash-secret}
  metrics-pw:
    external: true
    name: ${METRICS_PW:-metrics-pw}
  production-metis-hmac:
    external: true
    name: ${PRODUCTION_METIS_HMAC:-production-metis-hmac}
  production-magma-hmac:
    external: true
    name: ${PRODUCTION_MAGMA_HMAC:-production-magma-hmac}
  db-pw:
    external: true
    name: "magma_production_db_password"

networks:
  fe:
  db:
    external: true
    name: magma_db
  edge_bridge:
    external: true
  prometheus:
    external: true
