version: '3.8'
services:
  app_fe:
    environment:
      - APP_NAME=metis
      - METIS_ENV=production
    image: etnaagent/metis_app_fe:production
    networks:
      - edge_bridge
      - fe
    volumes:
      - app_public:/app/public:nocopy
      - data:/app/data/metis:ro
    # Notably, apache needs to start as super user but it immediately downgrades
    # its own user permissions after bootup.  See the includes.
    user: 0:3000 # su:browser
    configs:
      - source: browser.system.include
        target: /usr/opt/httpd.conf.d/browser.system.include
    deploy:
      replicas: 1
      labels:
        - autoupdate=true
      placement:
        constraints:
          - node.labels.volumes.big-shared == true
          - node.labels.volumes.data3 == true

  app_assets_deployer:
    environment:
      - APP_NAME=metis
      - METIS_ENV=production

    command: /bin/deploy.sh syncAssets -- true
    image: etnaagent/metis:production
    volumes:
      - app_public:/sync-assets:nocopy
    user: 0:3000
    deploy:
      labels:
        - autoupdate=true
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.volumes.big-shared == true

configs:
  browser.system.include:
    name: ${BROWSER_SYSTEM_INCLUDE:-browser.system.include}
    external: true
  config:
    external: true
    name: ${APP_CONFIG:-metis.production.yml}
  env:
    external: true
    name: ${ENV_CONFIG:-etna.production.yml}

secrets:
  user-hash-secret:
    external: true
    name: ${USER_HASH_SECRET:-user-hash-secret}
  metrics-pw:
    external: true
    name: ${METRICS_PW:-metrics-pw}
  production-metis-hmac:
    external: true
    name: ${PRODUCTION_METIS_HMAC:-production-metis-hmac}
  production-magma-hmac:
    external: true
    name: ${PRODUCTION_MAGMA_HMAC:-production-magma-hmac}
  db-pw:
    external: true
    name: "metis_production_db_password"

networks:
  fe:
  db:
  edge_bridge:
    external: true
  prometheus:
    external: true

volumes:
  app_public:
    name: metis_production_app_public
    driver: local
    driver_opts:
      type: nfs
      o: addr=mtetna-nfs1,nolock,noatime,suid,nodev,retry=16,proto=tcp,nfsvers=3
      device: ":/cache/metis/app_public"
  thumbnails:
    name: metis_production_thumbnails
    driver: local
    driver_opts:
      type: nfs
      o: addr=mtetna-nfs1,nolock,noatime,suid,nodev,retry=16,proto=tcp,nfsvers=3
      device: ":/cache/metis/thumbnails"
  data:
    name: metis_production_data
    driver: local
    driver_opts:
      type: local
      o: bind
      device: "/data3/metis"
  db:
    name: "metis_staging_db"
    driver: local
    driver_opts:
      type: nfs
      o: addr=mtetna-nfs1,nolock,noatime,suid,nodev,retry=16,proto=tcp,nfsvers=3,hard,intr
      device: ":/cache/postgres/metis-staging"
