version: '3.8'

services:
  postgres:
    image: postgres:10.12
    environment:
      POSTGRES_DB: 'metis'
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: developer
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.volumes.metis_${ENV}_db == true
    networks:
      - metis

  app:
    environment:
      APP_NAME: metis
      METIS_ENV: production
      METIS__PRODUCTION__DB__PASSWORD: "${DB_PASSWORD}"
      METIS__PRODUCTION__ROLLBAR__ACCESS_TOKEN: "${ROLLBAR_TOKEN}"
    command:
      - bash
      - -c
      - |
        set -e
        source /*.env.sh
        export METIS__PRODUCTION__USER_HASH_SECRET="$$(cat /run/secrets/user-hash-secret)"
        export METRICS_PW="$$(cat /run/secrets/metrics-pw)"
        exec /bin/deploy.sh migrate -- /app/bin/puma.sh
    image: etnaagent/metis:${ENV}
    volumes:
      - ${DATA_SOURCE}/metis/:/app/data/metis
      - /var/node_exporter/metrics.prom:/tmp/metrics.prom
    user: 1501:999 # metis:docker
    deploy:
      update_config:
        parallelism: 1
        order: start-first
      labels:
        - autoupdate=true
      placement:
        constraints:
          - node.labels.volumes.metis_${ENV}_data == true
    healthcheck:
      interval: 60s
      retries: 60
      start_period: 1s
      test: bash -c 'wget -O - http://localhost:3000 &>/dev/null || exit 1'
      timeout: 2s
    configs:
      - source: metis.config
        target: /app/config.yml
      - ${ENV}.etna.env.sh
    networks:
      - metis
      - prometheus

  app_fe:
    environment:
      APP_NAME: metis
      VULCAN_ENV: production
    image: etnaagent/metis_app_fe:${ENV}
    networks:
      - edge_bridge
      - metis
    volumes:
      - app_public:/app/public
      - ${DATA_SOURCE}/metis/:/app/data/metis:ro
    # Notable, apache needs to start as super user but it immediately downgrades
    # its own user permissions after bootup.  See the includes.
    user: 0:3000 # su:browser
    configs:
      - source: browser.system.include
        target: /usr/opt/httpd.conf.d/browser.system.include
    deploy:
      labels:
        - autoupdate=true
      restart_policy:
        condition: none
      placement:
        constraints:
        - node.labels.volumes.metis_${ENV}_app_public == true
        - node.labels.volumes.metis_data == true

  app_assets_deployer:
    environment:
      APP_NAME: metis
      VULCAN_ENV: production

    command: /bin/deploy.sh syncAssets -- true # Sync the assets to the shared data volume and stop.
    image: etnaagent/metis:${ENV}
    volumes:
      - app_public:/sync-assets:rw

    deploy:
      labels:
        - autoupdate=true
      restart_policy:
        condition: none
      mode: global
      placement:
        max_replicas_per_node: 1
        constraints: ["node.labels.volumes.metis_${ENV}_app_public == true"]

volumes:
  app_public:
  db:
    name: metis_${ENV}_db

configs:
  browser.system.include:
    external: true
  metis.config:
    external: true
  staging.etna.env.sh:
    external: true
    
secrets:
  user-hash-secret:
    external: true
  metrics-pw:
    external: true

networks:
  metis:
  edge_bridge:
    external: true
  prometheus:
    external: true
