version: '3.8'

services:
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD_FILE: /run/secrets/prefect-postgres-password
      POSTGRES_DB: prefect
    secrets:
      - prefect-postgres-password
    volumes:
      - prefect-db-data:/var/lib/postgresql/data
    networks:
      - prefect
    command:
      - "postgres"
      - "-c"
      - "max_connections=150"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.volumes.prefect-db == true
    healthcheck:
      test: pg_isready -q -d prefect -U developer || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 2s
    restart: always
    
  hasura:
    command:
      - sh
      - -c
      - |
        set -e
        export HASURA_GRAPHQL_DATABASE_URL="postgresql://developer:$$(cat /run/secrets/prefect-postgres-password)@prefect_postgres:5432/prefect"
        exec graphql-engine serve
    deploy:
      mode: replicated
      replicas: 1
    secrets:
      - prefect-postgres-password
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: warn
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
      HASURA_GRAPHQL_SERVER_PORT: '3000'
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 1s
      test: wget -O - http://localhost:$${HASURA_GRAPHQL_SERVER_PORT}/healthz &>/dev/null
        || exit 1
      timeout: 2s
    image: hasura/graphql-engine:v1.3.3
    networks:
      prefect: null
    restart: always

  graphql:
    command:
      - bash
      - -c
      - |
        set -e
        export PREFECT_SERVER__DATABASE__CONNECTION_URL="postgresql://developer:$$(cat /run/secrets/prefect-postgres-password)@prefect_postgres:5432/prefect"
        export PREFECT_SERVER__HASURA__ADMIN_SECRET="$$(cat /run/secrets/hasura-admin-secret)"
        prefect-server database upgrade -y
        exec python src/prefect_server/services/graphql/server.py
    secrets:
      - prefect-postgres-password
      - hasura-admin-secret
    environment:
      PREFECT_CORE_VERSION: 0.15.4
      PREFECT_SERVER_DB_CMD: prefect-server database upgrade -y
      PREFECT_SERVER__HASURA__HOST: prefect_hasura
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      interval: 20s
      retries: 60
      start_period: 1s
      test: curl --fail --silent "http://localhost:4201/health" &> /dev/null || exit
        1
      timeout: 2s
    image: prefecthq/server:core-0.15.4
    networks:
      prefect: null
    restart: always

  apollo:
    command:
      - bash
      - -c
      - |
        ./post-start.sh
        npm run serve
    environment:
      GRAPHQL_SERVICE_HOST: http://prefect_graphql
      GRAPHQL_SERVICE_PORT: 4201
      HASURA_API_URL: http://prefect_hasura:3000/v1alpha1/graphql
      PREFECT_API_HEALTH_URL: http://prefect_graphql:4201/health
      PREFECT_API_URL: http://prefect_graphql:4201/graphql/
      PREFECT_SERVER__TELEMETRY__ENABLED: "true"
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 1s
      test: curl --fail --silent "http://localhost:4200/.well-known/apollo/server-health"
        &> /dev/null || exit 1
      timeout: 2s
    image: prefecthq/apollo:core-0.15.4
    networks:
      prefect: null
      edge_bridge: null

    restart: always
  
  towel:
    command:
      - bash
      - -c
      - |
        export PREFECT_SERVER__HASURA__ADMIN_SECRET="$$(cat /run/secrets/hasura-admin-secret)"
        exec python src/prefect_server/services/towel/__main__.py
    environment:
      PREFECT_SERVER__HASURA__HOST: prefect_hasura
    image: prefecthq/server:core-0.15.4
    networks:
      prefect: null
    restart: always
    secrets:
      - hasura-admin-secret
  
  cli:
    command:
      - bash
      - -c
      - |
        export PREFECT__SERVER__HASURA__ADMIN_SECRET="$$(cat /run/secrets/hasura-admin-secret)"
        prefect backend server
        bash
    environment:
      PREFECT__SERVER__HASURA__HOST: prefect_hasura
      PREFECT__SERVER__ENDPOINT: http://prefect_apollo:4200
    image: prefecthq/server:core-0.15.4
    networks:
      prefect: null
    secrets:
      - hasura-admin-secret
    deploy:
      restart_policy:
        condition: none
        max_attempts: 1
    stdin_open: true
    tty: true
    
  ui:
    command: /intercept.sh
    environment:
      PREFECT_SERVER__APOLLO_URL: http://metis-stage.dsco.ucsf.edu/graphql
    healthcheck:
      interval: 30s
      retries: 3
      test: curl --fail --silent --head "http://localhost:8080/" &> /dev/null || exit 1
      timeout: 5s
    image: prefecthq/ui:core-0.15.4
    networks:
      prefect: null
      edge_bridge: null
    restart: always



networks:
  prefect:
  edge_bridge:
    external: true

volumes:
  prefect-db-data:

secrets:
  prefect-postgres-password:
    external: true
  hasura-admin-secret:
    external: true
  
