version: '3.8'

services:
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD_FILE: /run/secrets/prefect-postgres-password
      POSTGRES_DB: prefect
    secrets:
      - prefect-postgres-password
    volumes:
      - prefect-db-data:/var/lib/postgresql/data
    networks:
      - prefect
    command:
      - "postgres"
      - "-c"
      - "max_connections=150"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:

          - node.labels.volumes.prefect-db == true
    healthcheck:
      test: pg_isready -q -d prefect -U developer || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 2s
    restart: always
    
  hasura:
    command:
      - sh
      - -c
      - |
        set -e
        export HASURA_GRAPHQL_DATABASE_URL="postgresql://developer:$$(cat /run/secrets/prefect-postgres-password)@prefect_postgres:5432/prefect"
        exec graphql-engine serve
    depends_on:
    - postgres
    secrets:
      - prefect-postgres-password
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: warn
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
      HASURA_GRAPHQL_SERVER_PORT: '3000'
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 1s
      test: wget -O - http://prefect_hasura:$${HASURA_GRAPHQL_SERVER_PORT}/healthz &>/dev/null
        || exit 1
      timeout: 2s
    image: hasura/graphql-engine:v1.3.3
    networks:
      prefect: null
    ports:
    - published: 3000
      target: 3000
    restart: always

networks:
  prefect:

volumes:
  prefect-db-data:

secrets:
  prefect-postgres-password:
    external: true
