---
:production:
  :auth_redirect: https://janus.ucsf.edu
  :token_algo: RS256
  :token_name: JANUS_TOKEN
  :token_domain: ucsf.edu
  :token_life: 86400
  :log_file: "/dev/stdout"
  :log_level: info
  :rsa_public: |-
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3cmYfKvOUxKLgv/TQ9aG
    hMA4TCs2gQosmYejdE8I4Y39dSHtUnERX3ztMoesZVdhXU1GR7LWTfuOIze/H9q+
    x/IDx/KBBoiYV+oZ6tCRVV74lNJJpAEyRT5hAW9yW2/OTG2R6wlXc1oxjRfi+M38
    mMzNN/mR54Yzgr4Rch1NYCd/ZOt0zrBKuNg7xu17N1wDjc7XDVgCn4btgpwO3g8D
    wsiAXwnpbXgi1FP+7oiHiHPS07+CuKDafvLXqAVB2VymIR5muyWyayrxGjxyulZY
    TiDEPew/1TSBS+F8c4ZmAuH7fj+XX4ofWboZFrKl3R8V/041TdZX5nfOiLL3guDT
    V1fcc4gKfED4wI8bui0KDZqSTNYXsHNEm2r6y5VRhRwpRqFYT6YvAtiHrS9/U0L8
    rl8qoQWGG+bqepaBcQZ6GuPzWcTQfookI0LMQHpexAfBef1IQS7JJ7CrRgLD8ryS
    eolIQsOIX1fVTPUlY2x7liDaC49dnoZNDjMTy6bOiWGXzek0iF7qZd12nbDW5vUQ
    iJ3tahGjB3AbekXFGXNBOByW/qZrj0EHWWJMysZ2lDlTnAPtBmwwcF9YTZQA7XGO
    sPDtWvOVFzFxTEIPok1Cv/4dZDcVX4raeLaftV4PNY38o19E+ensWKeFUoA0a+wC
    VnOJnAt45Hq/mNZEBP2I7/MCAwEAAQ==
    -----END PUBLIC KEY-----
  :user_hash_secret: m8123Nasdz01Lapo2n-
  :magma:
    :host: https://magma.ucsf.edu
  :metis:
    :host: https://metis.ucsf.edu
  :timur:
    :host: https://timur.ucsf.edu
  :janus:
    :host: https://janus.ucsf.edu
  :polyphemus:
    :host: https://polyphemus.ucsf.edu
  :redcap:
    :host: https://redcap.ucsf.edu
  :vulcan:
    :host: https://vulcan.ucsf.edu
  :prometheus:
    :host: https://prometheus.dsco.ucsf.edu
  :grafana:
    :host: https://grafana.dsco.ucsf.edu
  :log_redact_keys: ''
  :metis_uid_name: METIS_UID
  :db:
    :password: LB3wxUenCD3EfnMhajTkVQ
  :rollbar:
    :access_token: c2ad65a7bd914858ab38047d1dfc3aa2

