source "http://rubygems.org"

ruby "~> 3.4"

gem 'mini_magick'
gem 'daru'
gem 'rltk'
gem 'filigree', '0.3.3'
gem 'fog-aws'
gem 'puma', '~> 5.6'
gem 'etna', path: '/etna'
gem 'pg'
gem 'sequel', '~> 5.57'
gem 'sequel_pg', :require=>'sequel'
gem "rack"
gem 'rack-throttle'
gem "jwt"
gem "rollbar"
gem "vcr" # For Etna::Client in recording mode.
gem "multipart-post"
gem 'ruby-vips'
gem "nokogiri"
gem "rake" # for mimemagick??
gem "concurrent-ruby"
gem "prometheus-client"
gem 'spreadsheet'
gem 'activerecord', '~> 7.1'
gem 'activesupport', '~> 7.1'
gem 'addressable', '~> 2.8.1'
# Pin yabeda family: 0.16+ changed with_tags API; pin until etna/instrumentation.rb is updated
gem "yabeda", "~> 0.11.0"
gem "yabeda-prometheus", "~> 0.8.0"
gem "yabeda-puma-plugin", "~> 0.6.0"
gem "curb"
gem "net-ssh"
gem "net-scp"
gem "net-sftp"
gem 'ed25519', '>= 1.2', '< 2.0'
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
gem 'connection_pool'
gem "rsync", "~> 1.0", ">= 1.0.9"
gem "json_schemer"

# stdlib gems extracted from Ruby default gems in Ruby 3.1-3.4
gem 'net-smtp'
gem 'net-pop'
gem 'net-imap'
gem 'ostruct'
gem 'base64'
gem 'logger'
gem 'csv'

group :test do
  gem 'rspec'
  gem 'rack-test', require: "rack/test"
  gem "pry", "~>0.14.2"
  gem "pry-byebug"
  gem "timecop"
  gem "webmock"
  gem "simplecov"
  gem 'factory_bot'
  gem 'net-http-persistent'
end
