source 'http://rubygems.org'

ruby '~> 2.5'

gem 'rack'
gem 'jwt'
gem 'rspec'
gem 'simplecov'
gem 'rack-test', require: "rack/test"
gem 'rollbar'
gem 'debase'
gem 'ruby-debug-ide'

group :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'timecop'
  gem 'webmock'
  gem 'net-http-persistent'
  gem 'multipart-post'
end
