version: '3.4'

networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

services:
  "prometheus_app":
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: /bin/sh -c
    user: 0:0
    command:
      - /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    networks:
      default:
      edge_net:
    extra_hosts:
      - 'metis.development.local:172.16.238.10'
      - 'prometheus.development.local:172.16.238.10'
      - 'janus.development.local:172.16.238.10'
      - 'timur.development.local:172.16.238.10'
      - 'rtemis.development.local:172.16.238.10'
      - 'archimedes.development.local:172.16.238.10'
      - 'polyphemus.development.local:172.16.238.10'

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'

  grafana:
    image: grafana/grafana:7.5.1
    container_name: grafana
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
    networks:
      default:
      edge_net:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 7100:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro