apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cat-ingestion-workflow-
  namespace: argo
spec:
  entrypoint: cat-ingestion
  onExit: write-run_metadata
  templates:
    - name: cat-ingestion
      steps:
        - - name: file-discovery
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: sftp_file_discovery
                - name: config_id
                  value: "{{inputs.parameters.config_id}}"
                - name: version_number
                  value: "{{inputs.parameters.version_number}}"
        - - name: c4-update
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: sftp_c4_uploader
                - name: config_id
                  value: "{{inputs.parameters.config_id}}"
                - name: version_number
                  value: "{{inputs.parameters.version_number}}"
        - - name: metis-update
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: sftp_metis_uploader
                - name: config_id
                  value: "{{inputs.parameters.config_id}}"
                - name: version_number
                  value: "{{inputs.parameters.version_number}}"
    - name: record-runtime-meta
      templateRef:
        name: record-runtime-meta-template
        template: record-runtime-meta