apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cat-ingestion-workflow-
  namespace: argo
spec:
  entrypoint: cat-ingestion
  onExit: record-runtime-meta
  imagePullSecrets:
    - name: hub.docker.com
  templates:
    - name: cat-ingestion
      steps:
        - - name: file-discovery
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: sftp_file_discovery
                - name: config_id
                  value: "{{workflow.parameters.config_id}}"
                - name: version_number
                  value: "{{workflow.parameters.version_number}}"
        - - name: c4-update
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: sftp_c4_uploader
                - name: config_id
                  value: "{{workflow.parameters.config_id}}"
                - name: version_number
                  value: "{{workflow.parameters.version_number}}"
        - - name: metis-update
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: sftp_metis_uploader
                - name: config_id
                  value: "{{workflow.parameters.config_id}}"
                - name: version_number
                  value: "{{workflow.parameters.version_number}}"
    - name: record-runtime-meta
      container:
        image: etnaagent/polyphemus:production
        command: ["/bin/sh", "-c"]
        args:
          - |
            /app/bin/polyphemus get_runtime_metadata "{{workflow.uid}}" \
            '$(argo get --output=json {{workflow.name}} -n {{workflow.namespace}})' \
            '$(argo logs {{workflow.name}})'