apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cat-ingestion-workflow-
  namespace: argo
spec:
  entrypoint: cat-ingestion
  onExit: write-run_metadata
  templates:
    - name: cat-ingestion
      steps:
        - - name: file-discovery
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: file_discovery
                - name: config_id
                  value: "{{inputs.parameters.config_id}}"
        - - name: c4-update
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: c4_update
                - name: config_id
                  value: "{{inputs.parameters.config_id}}"
        - - name: metis-update
            templateRef:
              name: run-job-template
              template: run-job
            arguments:
              parameters:
                - name: job
                  value: metis_update
                - name: config_id
                  value: "{{inputs.parameters.config_id}}"
    - name: write-run_metadata
      templateRef:
        name: write-run-metadata-template
        template: write-run_metadata
      arguments:
        parameters:
          - name: config_id
            value: "{{inputs.parameters.config_id}}"
