source 'https://rubygems.org'

ruby '2.5.7'

gem 'rack'
gem 'rack-throttle'
gem 'pg'
gem 'sequel'
gem 'etna', git: 'https://github.com/mountetna/monoetna.git', branch: 'refs/artifacts/gem-etna/58f4c58cb360d13a4e4f0e5bd644803bfd0be801'
gem 'jwt'

group :test do
  gem 'rspec'
  gem 'timecop'
  gem 'rack-test', require: "rack/test"
  gem 'factory_bot'
  gem 'simplecov'
  gem 'nokogiri'
  gem 'pry'
  gem 'database_cleaner'
end
