# Base for composed docker-compose.yml file.  See ./compose
version: "3.4"

# Network used route *.development.local back to apache for internal http
networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'
