#! /usr/bin/env bash
set -e
set -o pipefail

prog=$0
error() {
   echo "Whoops!  Looks like $1:$2 failed."
   echo "Please try rerunning $prog again."
   exit 1
}
trap 'error "${BASH_SOURCE}" "${LINENO}"' ERR

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

shopt -s globstar

cd $DIR/..

for compose_file in **/docker-compose.yml; do
    for original_image in $(cat $compose_file | grep image | sed -e 's/.*image: \(.*\)/\1/g' | uniq); do
        [[ $original_image =~ [^/]*/ ]] && continue # not a local image

        echo Tagging $original_image into $1/$original_image
        sed -i $compose_file -e "s/image: ${original_image}/image: ${1}\/${original_image}/g"
    done
done
