apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: metis-linker-workflow-
spec:
  entrypoint: metis-linker
  templates:
    - name: metis-linker
      steps:
        - - name: read-config
            template: run-job
            arguments:
              parameters:
                - name: workflow
                  value: cat_ingestion
                - name: job
                  value: read_config
        - - name: collect-tail
            template: run-job
            arguments:
              parameters:
                - name: workflow
                  value: cat_ingestion
                - name: job
                  value: collect_tail
        - - name: process-tail
            template: run-job
            arguments:
              parameters:
                - name: workflow
                  value: cat_ingestion
                - name: job
                  value: process_tail
        - - name: post-update
            template: run-job
            arguments:
              parameters:
                - name: workflow
                  value: cat_ingestion
                - name: job
                  value: post_update
    - name: run-job
      inputs:
        parameters:
          - name: workflow
          - name: job
      container:
        image: base_etna
        command:
          - sh
          - -c
        args:
          - |
            bin/run_job {{inputs.parameters.workflow}} {{inputs.parameters.job}}
        env:
          - name: ARGO_WORKFLOW_ID
            value: "{{workflow.id}}"
          - name: WORKFLOW_TABLE
            value: cat_ingestion
          - name: WORKFLOW_NAME
            value: "{{inputs.parameters.workflow}}"
          - name: JOB_NAME
            value: "{{inputs.parameters.job}}"
