name 'base_v2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures base_v2'
long_description 'Installs/Configures base_v2'
version '0.1.0'
chef_version '>= 14.0'

depends 'docker'
