require_relative './workflows/crud_workflow'
require_relative './workflows/file_linking_workflow'
require_relative './workflows/model_synchronization_workflow'
require_relative './workflows/file_attributes_blank_workflow'
require_relative './workflows/update_attributes_by_csv_workflow'