name: Run Ruby tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      TIMUR_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Set up database
        env:
          PGHOST: 127.0.0.1
          PGUSER: developer
        run: |
          cp config.yml.test config.yml
          bin/timur create_db
          bin/timur migrate
      - name: Run test suite
        run: |
          bundle exec rspec spec/
