version: "3.4"
volumes:
  data-dir:
    driver: local

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./certs:/root/certs
      - ./docker-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - data-dir:/app/data:rw
    ports:
      - "443:443"
      - "80:80"
