include ../make-base/stubs.mk
include ../make-base/docker-compose.mk
app_service_name:=airflow_ui

# baseTag:=$(shell basename "$$(pwd)")
# dockerOptions:=-u $(shell id -u):0 -v $$PWD/opt/plugins:/opt/airflow/plugins -v /var/run/docker.sock:/var/run/docker.sock:ro

