networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

version: '3.4'

volumes:
  archimedes-virtualenv:
    driver: local
  archimedes-pycharm-opt:
    driver: local
  archimedes-exec:
    driver: local

services:
  archimedes_app:
    image: archimedes-base
    volumes:
      - .:/app:delegated
      - archimedes-virtualenv:/root/.cache/pypoetry/virtualenvs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - archimedes-pycharm-opt:/opt/.pycharm_helpers
      - archimedes-exec:/archimedes-exec
      - ../vulcan/lib/server/workflows/scripts:/app/vulcan_scripts
      - ../etna/packages/etna-py/:/etna-py/
    environment:
      HOST_DIR: $PWD
    entrypoint: /entrypoints/development.sh
    command: echo hello!
