version: "3.4"

volumes:
  archimedes-virtualenv:
    driver: local
  archimedes-pycharm-opt:
    driver: local



services:
  archimedes_app:
    image: archimedes-base
    volumes:
    - .:/app:delegated
    - archimedes-virtualenv:/root/.cache/pypoetry/virtualenvs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - archimedes-pycharm-opt:/opt/.pycharm_helpers
#    - /tmp:/tmp:delegated
    environment:
      HOST_DIR: $PWD
    entrypoint: /entrypoints/development.sh
    command: echo hello!
