Bootstrap: docker
From: ubuntu:20.04

# standing on the shoulders of giants, like Arjun Rao who helped tremendously
# with v1-3 of the non archimedes R Singularity containers, and Rebecca who
# helped both with v4 of the non archimedes R Singularity containers as well as
# directly contributed to this container,
# and Jeremy Nicklas (https://github.com/nickjer/singularity-rstudio)

%environment
    export R_LIBS_SITE=/usr/lib/R/library
    export R_LIBS=/usr/lib/R/library
    export R_LIBS_USER=/usr/lib/R/library

%labels
    Author Daniel Bunis
    Maintainer Daniel Bunis
    R_Version 4.4
    python_version 3.8
    # Seurat_Version 4.3.0

%setup
    # Set up the working directory
    mkdir -p /app

%files
    install_deps.R /app/

%runscript
    cd /app
    exec "${@}"

%post
    # TZ fix 
    TZ=America/Los_Angeles
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime 
    echo $TZ > /etc/timezone
    echo "start time is:"
    date

    # Software versions
    export R_VERSION=4.4
    echo "export R_VERSION=${R_VERSION}" >> $SINGULARITY_ENVIRONMENT
    
    # Configure default locale & other time vars
    export DEBIAN_FRONTEND="noninteractive"
    apt-get update && apt-get install -y --no-install-recommends locales
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen en_US.utf8
    /usr/sbin/update-locale LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
    export LC_TIME=en_US.UTF-8
    export LC_MONETARY=en_US.UTF-8
    export LC_PAPER=en_US.UTF-8
    export LC_MEASUREMENT=en_US.UTF-8
    
    # get ubuntu utils
    apt-get update && apt-get install -y --no-install-recommends \
        software-properties-common \
        dirmngr \
        wget \
        curl
    
    # install python & python utils
    add-apt-repository -y ppa:cran/libgit2
    add-apt-repository -y ppa:deadsnakes/ppa
    add-apt-repository -y ppa:ubuntugis/ppa
    apt-get update && apt-get install -y \
        python3.8 \
        python3.8-dev \
        python3.8-distutils \
        python3.8-tk \
        gdal-bin \
        libgdal-dev \
        libssh2-1-dev \
        libgit2-dev

    curl https://bootstrap.pypa.io/get-pip.py -o /opt/get-pip.py
    python3.8 /opt/get-pip.py
    pip3.8 install -U pip setuptools
    # Specifically use pandas 1.1.5 since there's a bug in pandas < 1.1.5 that prevents it from reading
    # files with > 1M lines
    pip3.8 install \
        pandas==1.1.5 \
        setuptools \
        louvain \
        leidenalg \
        macs3

    mkdir /opt/pybin
    ln -s /usr/local/bin/pip3.8 /opt/pybin/pip
    ln -s /usr/local/bin/pip3.8 /opt/pybin/pip3
    ln -s /usr/bin/python3.8 /opt/pybin/python
    ln -s /usr/bin/python3.8 /opt/pybin/python3

    export PATH=/opt/pybin:${PATH}
    echo "export PATH=/opt/pybin:${PATH}" >> $SINGULARITY_ENVIRONMENT
    
    # install R
    wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | \
    tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
    add-apt-repository \
        "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
    
    apt-get update
    apt-get install -y \
        r-base=${R_VERSION}* \
        r-base-core=${R_VERSION}* \
        r-base-dev=${R_VERSION}* \
        r-recommended=${R_VERSION}* \
        r-base-html=${R_VERSION}* \
        r-doc-html=${R_VERSION}*

    # Add a default CRAN mirror
    echo "options(repos = c(CRAN = 'https://cloud.r-project.org/'), download.file.method = 'libcurl')" >> /usr/lib/R/etc/Rprofile.site

    # Add a directory for host R libraries
    mkdir -p /usr/lib/R/library
    echo "R_LIBS_SITE=/usr/lib/R/library" >> /usr/lib/R/etc/Renviron.site
    
    # Set up the reticulate python version
    echo "RETICULATE_PYTHON=/usr/bin/python3.8" >> /usr/lib/R/etc/Renviron.site

    apt-get update && apt-get install -y --no-install-recommends \
        libcurl4-openssl-dev \
        libssl-dev \
        libopenblas-dev \
        gnupg \
        bash-completion \
        git \
        build-essential \
        libgeos-dev \
        libmagick++-dev \
        libcairo2-dev \
        libfontconfig1-dev \
        libhdf5-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        cmake \
        libboost-filesystem-dev \
        libfreetype6-dev \
        libgsl-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff5 \
        libtiff5-dev \
        libudunits2-dev \
        libxml2-dev \
        libxt-dev

    # Install R packages
    cd /app
    Rscript install_deps.R

    # Cleanup
    rm -rf /var/lib/apt/lists/*
    rm -f /app/install_deps.R
    rm -rf /opt/get-pip.py

    echo "end time is:"
    date 

%runscript
    echo "Container is ready!"
