networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

version: '3.4'

volumes:
  archimedes-exec:
    driver: local

services:
  archimedes-r_app:
    image: archimedes-r
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - archimedes-exec:/archimedes-exec
      - ../vulcan/lib/server/workflows/scripts:/app/vulcan_scripts
    environment:
      HOST_DIR: $PWD
    # entrypoint: /entrypoints/development.sh
    command: echo hello!
