networks:
  edge_net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'

version: '3.4'

volumes:
  archimedes-global-node-modules:
    driver: local
  archimedes-r-libs:
    driver: local
  archimedes-exec:
    driver: local

services:
  archimedes-r_app:
    image: archimedes-r
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
      - archimedes-r-libs:/root/.cache/R/renv/library/app-369-b32273d8/R-4.1/x86_64-pc-linux-gnu
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - archimedes-exec:/archimedes-exec
      - ../vulcan/lib/server/workflows/scripts:/app/vulcan_scripts
    environment:
      HOST_DIR: $PWD
    entrypoint: /entrypoints/development.sh
    command: echo hello!
