version: '3.4'

services:
  deployer_app:
    image: deployer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deployer.sh:/bin/deployer
      - ./test.sh:/test.sh
      - ./TestDockerFile:/TestDockerFile

