BootStrap: localimage
From: /home/danb/archimedes-py-base/archimedes-py-base.sif

%labels
    Author Daniel Bunis
    Maintainer Daniel Bunis
    python_version 3.8
    poetry_version 1.1.15

%environment
    export PATH="/app/bin:/opt/poetry/bin:$PATH"
    export POETRY_HOME="/opt/poetry"
    export POETRY_CACHE_DIR="/app/.cache/pypoetry"

%files
    functions /app/archimedes/functions
    poetry.lock /app/poetry.lock
    pyproject.toml /app/pyproject.toml

%post
    # Singularity's equivalent of Docker's RUN command
    # The environment variables like FULL_BUILD would be available here
    cd /app
    
    # Install dependencies
    export PATH="/app/bin:/opt/poetry/bin:$PATH"
    export POETRY_HOME="/opt/poetry"
    echo "export POETRY_HOME=${POETRY_HOME}" >> $SINGULARITY_ENVIRONMENT
    export POETRY_CACHE_DIR="/app/.cache/pypoetry"
    echo "export POETRY_CACHE_DIR=${PYTHON_VERSION}" >> $SINGULARITY_ENVIRONMENT
    poetry config virtualenvs.create false
    poetry install

%runscript
    exec "${@}"
