# NOTE: add this to github ci everytime we merge to production
# kubectl apply -f workflows/templates/run-job-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: run-job-template
  namespace: argo
spec:
  templates:
    - name: run-job
      inputs:
        parameters:
          - name: job
          - name: config_id
          - name: version_number
      container:
        image: etnaagent/polyphemus:production
        imagePullPolicy: Always
        imagePullSecrets: 
          - name: hub.docker.com
        command:
          - sh
          - -c
        args:
        # Refactor this once we sort out how to use file secrets in the argo namespace
          - |
            echo "password: $DB_PASSWORD" > /app/db-password; cp /run/config/*.yml /app; /app/bin/polyphemus run_job {{inputs.parameters.job}} {{inputs.parameters.config_id}} {{inputs.parameters.version_number}}
        env:
          - name: KUBE_ID
            value: "{{workflow.uid}}"
          - name: WORKFLOW_NAME 
            value: "{{workflow.name}}"
          - name: APP_NAME
            value: polyphemus
          - name: POLYPHEMUS_ENV
            value: production
          - name: ETNA__PRODUCTION_FILE
            value: /run/config/env.yml
          - name: ETNA__PRODUCTION__DB_FILE
            value: /app/db-password
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: workflows-polyphemus-app-secrets
                key: db-password
        volumeMounts:
          - name: config-volume
            mountPath: /run/config
      volumes:
      - name: config-volume
        configMap:
          name: workflows-polyphemus-app-config
