source 'https://rubygems.org'

gem 'sequel'
gem 'pg'
gem 'etna', git: 'https://github.com/mountetna/monoetna.git', branch: 'refs/artifacts/gem-etna/25d90094b401b5c45f2dafbd4049398c0a44e83c'

group :development, :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'pry'
  gem 'pry-byebug'
  gem 'webmock'
  gem 'debase'
  gem 'ruby-debug-ide'
  gem 'database_cleaner'
  gem 'vcr'
end
