source 'https://rubygems.org'

gem 'sequel'
gem 'pg'
gem 'etna', git: 'https://github.com/mountetna/monoetna.git', branch: 'refs/artifacts/gem-etna/854c702f081f975d0a1619ed929b850fb6b6d599'

group :development, :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'pry'
  gem 'pry-byebug'
  gem 'webmock'
  gem 'debase'
  gem 'ruby-debug-ide'
  gem 'database_cleaner'
  gem 'vcr'
end
