name: Run Python tests
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '*/*/*'
      - '!master'
      - '!swarm/stacks'
      - '!production'
      - '!staging'
      - '!production-build'
      - '!staging-build'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -p "${DOCKER_TOKEN}" -u etnaagent
      - name: Setup Python
        id: etna-py-setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run etna-py tests
        id: etna_py_test
        env:
          IMAGES_PREFIX: etnaagent/
          IS_CI: 1
          CI_SECRET: ${{ secrets.CI_SECRET }}
          IMAGES_POSTFIX: :master
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd etna/packages/etna-py
          pip install .
          poetry run pytest
