name: Run tests
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '*/*/*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -p "${DOCKER_TOKEN}" -u etnaagent
      - name: Download all images
        env:
          IMAGES_PREFIX: etnaagent/
          IS_CI: 1
          IMAGES_POSTFIX: :master
        run: |
          ./bin/x-all-images docker pull %
      - name: Setup Python
        id: magby_setup_py
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Run Magby tests
        id: magby_first_test_run
        env:
          IMAGES_PREFIX: etnaagent/
          IS_CI: 1
          CI_SECRET: ${{ secrets.CI_SECRET }}
          IMAGES_POSTFIX: :master
        run: |
          python -m pip install --upgrade pip
          pip install etna/packages/magby/
          python etna/packages/magby/tests/test_Magby.py
          python etna/packages/magby/tests/test_Magma.py
      - name: Run geoline tests
        id: geoline_first_test_run
        env:
          IMAGES_PREFIX: etnaagent/
          IS_CI: 1
          CI_SECRET: ${{ secrets.CI_SECRET }}
          IMAGES_POSTFIX: :master
        run: |
          python -m pip install --upgrade pip
          pip install geoline/
          python geoline/tests/test_Geoline.py
          python geoline/tests/test_geoUtils.py
          python geoline/tests/test_TemplateTree.py
