name: Run Ruby tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Fetch Magma and compile the gem
        run: |
          git clone https://github.com/mountetna/magma.git
          cd magma/gem
          gem build magma
          mv magma-0.5.1.gem ../../vendor/bundle/
      - name: Bundle install Gems
        run: |
          gem install bundler -v 2.1.4
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run test suite
        run: |
          bundle exec rspec spec/
