name: Build and upload staging images
on:
  push:
    branches:
      - staging

jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Arbitrarily deep in order for find-parent-pr-merge.sh to work.
          fetch-depth: 10
      - name: docker login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -p "${DOCKER_TOKEN}" -u etnaagent
      - name: Test + Push Release
        env:
          PUSH_IMAGES: 1
          IMAGES_PREFIX: etnaagent/
          IMAGES_POSTFIX: :staging
          NO_TEST: 1
        run: make -j 4 release

