name: Build and upload staging images
on:
  push:
    branches:
      - staging

# Ensure only one of these builds at a given time.
concurrency:
  group: staging-build
  cancel-in-progress: true

jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_ACCESS_TOKEN }}
      - name: docker login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -p "${DOCKER_TOKEN}" -u etnaagent
      - name: Build & Push staging tag images to dockerhub
        env:
          IS_CI: 1
          PUSH_IMAGES: 1
          IMAGES_PREFIX: etnaagent/
          IMAGES_POSTFIX: :staging
          NO_TEST: 1
        run: |
          make -j 4 release
          git push origin HEAD:staging-build --force
