name: Sync subtrees
on:
  push:
    branches:
      - master

jobs:
  update-artifacts-and-refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.name 'GithubAction'
          git config --global user.email 'mountetna@users.noreply.github.com'
          git status
      - name: Reattach HEAD to Head Ref
        run: git checkout $(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')
        if: github.head_ref != ''
      - name: Reattach HEAD to Head Ref
        run: git checkout $(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')
        if: github.head_ref == ''
      - name:  Push npm artifacts and update package.json
        run: |
          bin/update-package-references
          git status
          git add .
          git commit -m "Updated package.json references to artifacts"
          git push
  sync-to-and-from-subtrees:
    runs-on: ubuntu-latest
    needs: update-artifacts-and-refs
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.SYNC_ACCESS_TOKEN }}
      - name: Configure git
        run: |
          git config --global user.name 'GithubAction'
          git config --global user.email 'mountetna@users.noreply.github.com'
          git config --global core.mergeoptions --no-edit
      - name:  sync-subtrees
        env:
          IS_CI: true
        run: |
          bin/pull-subtrees master
          bin/push-subtrees master
          bin/pull-subtrees master
          git push
