name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker images
      run: |
        make build
    - name: Start up services
      run: |
        make up
        sleep 5
        make ps
        make logs

    - name: Run metis test suite
      id: metis_first_test_run
      run: |
        make -C metis test
    - name: Run test suite again to detect flaky failures
      if: ${{ steps.metis_first_test_run.outcome == 'success' }}
      run: |
        make -C metis test

    - name: Run janus test suite
      id: janus_first_test_run
      run: |
        make -C janus test
    - name: Run test suite again to detect flaky failures
      if: ${{ steps.janus_first_test_run.outcome == 'success' }}
      run: |
        make -C janus test

    - name: Run etna test suite
      id: etna_first_test_run
      run: |
        make -C etna test
    - name: Run test suite again to detect flaky failures
      if: ${{ steps.etna_first_test_run.outcome == 'success' }}
      run: |
        make -C etna test
